# Generated by Django 3.1 on 2020-09-03 15:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0005_auto_20200903_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='user_name',
            field=models.EmailField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=30),
        ),
    ]
